= HTML to JSON Transformation Policy

ifdef::env-github[]
image:https://ci.gravitee.io/buildStatus/icon?job=gravitee-io/gravitee-policy-html-json/master["Build status", link="https://ci.gravitee.io/job/gravitee-io/job/gravitee-policy-html-json/"]
image:https://badges.gitter.im/Join Chat.svg["Gitter", link="https://gitter.im/gravitee-io/gravitee-io?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge"]
endif::[]

== Scope

|===
|onRequest|onResponse|onRequestContent|onResponseContent
||||X
|===

== Description

The HTML to JSON transformation policy lets you apply a transformation on the response content.

This policy is based on the https://jsoup.org[jsoup] HTML parser.
The only thing you have to do using Gravitee.io API Management is to provide your JSON field names with the
associated selectors.

== Configuration

You can configure the policy with the following options :

|===
|Property |Required |Description |Type
|jsonName |true|The JSON field name where to put the result of the selection|String
|selector |true|HTML/CSS selector used to select an element and get the text|String
|array    |false|Used to now if the selection should be returned as an array or not|Boolean
|===


[source, json]
.Sample
----
"html-json": {
    "selectors":
        [
            {
                "array": false,
                "jsonName": "test",
                "selector": ".class h1"
            },
            {
                "array": true,
                "jsonName": "testArray",
                "selector": ".container ul"
            }
        ]
    }
}
----
